export const PERMISSIONS = {
  USER: {
    CREATE: "USER:CREATE",
    READ: "USER:READ",
    UPDATE: "USER:UPDATE",
    DELETE: "USER:DELETE",
    CHANGE_STATUS: "USER:CHANGE_STATUS",
    ASSIGN_ROLE: "USER:ASSIGN_ROLE",
  },

  ROLE: {
    CREATE: "ROLE:CREATE",
    READ: "ROLE:READ",
    UPDATE: "ROLE:UPDATE",
    DELETE: "ROLE:DELETE",
    ASSIGN_PERMISSION: "ROLE:ASSIGN_PERMISSION",
  },

  GROUP: {
    CREATE: "GROUP:CREATE",
    READ: "GROUP:READ",
    UPDATE: "GROUP:UPDATE",
    DELETE: "GROUP:DELETE",
    MANAGE_USERS: "GROUP:MANAGE_USERS",
    MANAGE_ROLES: "GROUP:MANAGE_ROLES",
  },

  DEPARTMENT: {
    CREATE: "DEPARTMENT:CREATE",
    READ: "DEPARTMENT:READ",
    UPDATE: "DEPARTMENT:UPDATE",
    DELETE: "DEPARTMENT:DELETE",
  },

  PERMISSION: {
    READ: "PERMISSION:READ",
  },

  AUDIT: {
    READ: "AUDIT:READ",
  },
};