export const PERMISSIONS = {
  USER: {
    CREATE: "USER:CREATE",
    READ: "USER:READ",
    UPDATE: "USER:UPDATE",
    DELETE: "USER:DELETE",
    CHANGE_STATUS: "USER:CHANGE_STATUS",
    ASSIGN_ROLE: "USER:ASSIGN_ROLE",
  },

  ROLE: {
    CREATE: "ROLE:CREATE",
    READ: "ROLE:READ",
    UPDATE: "ROLE:UPDATE",
    DELETE: "ROLE:DELETE",
    ASSIGN_PERMISSION: "ROLE:ASSIGN_PERMISSION",
  },

  DEPARTMENT: {
    CREATE: "DEPARTMENT:CREATE",
    READ: "DEPARTMENT:READ",
    UPDATE: "DEPARTMENT:UPDATE",
    DELETE: "DEPARTMENT:DELETE",
  },

  PERMISSION: {
    READ: "PERMISSION:READ",
  },

  AUDIT: {
    READ: "AUDIT:READ",
  },
};